name: "Build PDFs"
on:
  workflow_dispatch:
  push:
    branches:
    - master
    tags:
    - 'r*'
permissions:
  contents: write
jobs:
  build:
    name: Build PDFs
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    - uses: DeterminateSystems/nix-installer-action@main
    - uses: DeterminateSystems/magic-nix-cache-action@main
    - name: Build PDFs
      run: |
        nix build --print-build-logs --print-out-paths
        if ! nix build --rebuild --keep-failed; then
          diff -ar $(nix eval --raw){,.check}
          false
        fi
    - uses: actions/upload-artifact@main
      with:
        path: result/*
    - uses: softprops/action-gh-release@master
      if: startsWith(github.ref, 'refs/tags/r')
      with:
        files: result/*
